import Head from "next/head";
import { Skeleton } from "@mui/material";
import React from "react";

const Fallback = () => {
  return (
    <>
      <Head>
        <title>PCSHS Announcement</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Skeleton
        variant="rectangular"
        width="100%"
        height={480}
        sx={{ mb: 2 }}
      />
      <Skeleton variant="rectangular" width="40%" height={20} sx={{ mb: 2 }} />
      <Skeleton variant="rectangular" width="100%" height={80} sx={{ mb: 2 }} />
    </>
  );
};

export default Fallback;
