import { Button, Container, Divider, Typography, Box } from "@mui/material";
import { ReactNode } from "react";
import Head from "next/head";
import Link from "next/link";

const AdmissionInfo = ({
  children,
  title,
}: {
  children: ReactNode;
  title: string;
}) => {
  return (
    <>
      <Box display="flex" flexDirection="column" width="100%" mb={4}>
        <Typography variant="h5" align="center" fontWeight={700}>
          {title}
        </Typography>
        <Divider />
        <Typography variant="h6" paragraph align="justify" mt={2}>
          {children}
        </Typography>
      </Box>
    </>
  );
};

const Admission = () => {
  return (
    <>
      <Head>
        <title>PCSHS Admissions</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box display="flex" flexDirection="column" height="100%">
        <Container>
          <AdmissionInfo title={"Student Retention Policy"}>
            As per Sangguniang Panlungsod Ordinance No. 28, Series of 2004, the
            Pasig City Science High School is mandated to provide a more
            intensive and advanced secondary education program with emphasis in
            Science, Technology, Engineering and Mathematics (STEM). In order to
            ensure quality education and deserving graduates, a Student
            Retention Policy is implemented for strict compliance. Hence, a
            minimum final grade requirement is observed.
          </AdmissionInfo>
          <AdmissionInfo title={"Minimum Grade Requirement"}>
            GENERAL WEIGHTED AVERAGE of 85% with no final grade below 80% in any
            subject, homeroom, and deportment.
          </AdmissionInfo>
          <AdmissionInfo title={"Regular Student"}>
            A student who has satisfactorily met the minimum grade as stated
            above is considered student of Regular Status and is automatically
            qualified for promotion to the next grade level.
          </AdmissionInfo>
          <AdmissionInfo title={"Student on Probation"}>
            A regular student who has no final grade below 80% in any subject
            but whose general weighted average is below 85% (rounded-off) will
            be enrolled on probation. <br />
            <br /> A regular student whose general weighted average is 85%
            (rounded-off) but with grade below 80% in one (1) subjects will be
            enrolled on probation. <br />
            <br /> A student who will be enrolled on probation in the next level
            must enroll with their parents who will sign a contract for a Grade
            Compliance Requirement. <br />
            <br /> A student on probation must meet the grade compliance
            requirement in all subject areas in order to regain his/her status
            as a regular student. Otherwise he/she losses the qualification for
            promotion.
          </AdmissionInfo>
          <AdmissionInfo title={"Student For Transfer"}>
            A student who has a general weighted average below 85% and has
            received a final grade of below 80% in one (1) subject. <br />{" "}
            <br />
            A student who has a general weighted average of 85% and has received
            final grades below 80% in at least two (2) subjects. <br />
            <br /> A student who failed any one (1) subject. <br /> <br /> A
            student who is enrolled on a probationary status and who is not able
            to regain his/her qualification as a regular student at the end of
            the school year.
          </AdmissionInfo>
        </Container>
        <Box height="400px" sx={{ backgroundColor: "#03045e" }} pt={8} pb={8}>
          <Container
            sx={{
              display: "flex",
              justifyContent: "center",
              alignItems: "center",
              flexDirection: "column",
              color: "white",
            }}
          >
            <Typography variant="h3" align="center" fontWeight={800} mb={4}>
              Do you have what it takes to be a PASCIAN?
            </Typography>

            <Link href="/apply/process">
              <Button
                variant="outlined"
                sx={{ width: "480px", height: "80px", color: "#e9c46a" }}
                color="warning"
              >
                <Typography variant="h4">Apply Now</Typography>
              </Button>
            </Link>
          </Container>
        </Box>
      </Box>
    </>
  );
};

export default Admission;
