import {
  Button,
  Container,
  Divider,
  Fade,
  Grow,
  Typography,
  useMediaQuery,
  useTheme,
} from "@mui/material";
import { Box } from "@mui/system";
import { ReactNode } from "react";
import Head from "next/head";
import VisibilitySensor from "react-visibility-sensor";
import Link from "next/link";

const AdmissionInfo = ({
  children,
  title,
}: {
  children: ReactNode;
  title: string;
}) => {
  const theme = useTheme();
  const xl = useMediaQuery(theme.breakpoints.only("xl"));
  const sm = useMediaQuery(theme.breakpoints.down("md"));
  return (
    <>
      <VisibilitySensor partialVisibility>
        {({ isVisible }) => (
          <Fade in={isVisible} timeout={1500}>
            <Box display="flex" flexDirection="column" width="100%" mb={4}>
              <Typography
                variant="h5"
                gutterBottom
                align="center"
                mr={xl ? 16 : 2}
                ml={xl ? 16 : 2}
              >
                {title}
              </Typography>

              <Divider />

              <Typography
                variant={sm ? "body1" : "h6"}
                paragraph
                align="center"
                mt={2}
                mr={xl ? 16 : 2}
                ml={xl ? 16 : 2}
              >
                {children}
              </Typography>
            </Box>
          </Fade>
        )}
      </VisibilitySensor>
    </>
  );
};

const Admission = () => {
  const theme = useTheme();
  const sm = useMediaQuery(theme.breakpoints.down("md"));
  return (
    <>
      <Head>
        <title>PCSHS Admissions</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box display="flex" flexDirection="column" height="100%">
        <Container>
          <AdmissionInfo title={"Student Retention Policy"}>
            As per Sangguniang Panlungsod Ordinance No. 28, Series of 2004, the
            Pasig City Science High School is mandated to provide a more
            intensive and advanced secondary education program with emphasis in
            Science, Technology, Engineering and Mathematics (STEM). In order to
            ensure quality education and deserving graduates, a Student
            Retention Policy is implemented for strict compliance. Hence, a
            minimum final grade requirement is observed.
          </AdmissionInfo>
          <AdmissionInfo title={"Minimum Grade Requirement"}>
            GENERAL WEIGHTED AVERAGE of 85% with no final grade below 80% in any
            subject, homeroom, and deportment.
          </AdmissionInfo>
          <AdmissionInfo title={"Regular Student"}>
            A student who has satisfactorily met the minimum grade as stated
            above is considered student of Regular Status and is automatically
            qualified for promotion to the next grade level.
          </AdmissionInfo>
          <AdmissionInfo title={"Student on Probation"}>
            A regular student who has no final grade below 80% in any subject
            but whose general weighted average is below 85% (rounded-off) will
            be enrolled on probation. <br />
            <br /> A regular student whose general weighted average is 85%
            (rounded-off) but with grade below 80% in one (1) subjects will be
            enrolled on probation. <br />
            <br /> A student who will be enrolled on probation in the next level
            must enroll with their parents who will sign a contract for a Grade
            Compliance Requirement. <br />
            <br /> A student on probation must meet the grade compliance
            requirement in all subject areas in order to regain his/her status
            as a regular student. Otherwise he/she losses the qualification for
            promotion.
          </AdmissionInfo>
          <AdmissionInfo title={"Student For Transfer"}>
            A student who has a general weighted average below 85% and has
            received a final grade of below 80% in one (1) subject. <br />{" "}
            <br />
            A student who has a general weighted average of 85% and has received
            final grades below 80% in at least two (2) subjects. <br />
            <br /> A student who failed any one (1) subject. <br /> <br /> A
            student who is enrolled on a probationary status and who is not able
            to regain his/her qualification as a regular student at the end of
            the school year.
          </AdmissionInfo>
        </Container>
        <Box height="400px" sx={{ backgroundColor: "#03045e" }} pt={8} pb={8}>
          <Container
            sx={{
              display: "flex",
              justifyContent: "center",
              alignItems: "center",
              flexDirection: "column",
              color: "white",
            }}
          >
            <VisibilitySensor>
              {({ isVisible }) => (
                <>
                  <Grow in={isVisible} timeout={1500}>
                    <Typography
                      variant={sm ? "h4" : "h3"}
                      align="center"
                      gutterBottom
                      mt={4}
                    >
                      Do you have what it takes to be a PASCIAN?
                    </Typography>
                  </Grow>

                  <Link passHref href="/apply/process">
                    <Grow in={isVisible} timeout={2000}>
                      <Button
                        component="a"
                        variant="outlined"
                        sx={{
                          width: sm ? "240px" : "480px",
                          height: "80px",
                          color: "#e9c46a",
                        }}
                        color="warning"
                      >
                        <Typography variant={sm ? "h6" : "h4"}>
                          Apply Now
                        </Typography>
                      </Button>
                    </Grow>
                  </Link>
                </>
              )}
            </VisibilitySensor>
          </Container>
        </Box>
      </Box>
    </>
  );
};

export default Admission;
