import {
  Container,
  Typography,
  Box,
  styled,
  Table,
  TableBody,
  TableCell,
  tableCellClasses,
  TableHead,
  TableRow,
} from "@mui/material";
import Head from "next/head";
import { PSATRows } from "../../utils/staticResource";
import { ReactNode } from "react";

const StyledTableCell = styled(TableCell)(({ theme }) => ({
  [`&.${tableCellClasses.head}`]: {
    backgroundColor: "#03045e",
    color: theme.palette.common.white,
  },
  [`&.${tableCellClasses.body}`]: {
    fontSize: "18px",
  },
}));

const StyledTableRow = styled(TableRow)(({ theme }) => ({
  "&:nth-of-type(odd)": {
    backgroundColor: theme.palette.action.hover,
  },
  "&:last-child td, &:last-child th": {
    border: 0,
  },
}));

const ApplyInformation = ({
  children,
  backgroundImage,
  title,
}: {
  children: ReactNode;
  backgroundImage: string;
  title: string;
}) => {
  return (
    <Box
      sx={{
        height: "400px",
        backgroundImage,
        backgroundAttachment: "fixed",
        backgroundSize: "cover",
        backgroundRepeat: "no-repeat",
        mb: 4,
      }}
    >
      <Container
        sx={{
          display: "flex",
          alignItems: "center",
          justifyContent: "center",
          flexDirection: "column",
          height: "100%",
          backdropFilter: "blur(2px) brightness(60%)",
        }}
      >
        <Typography
          variant="h3"
          fontWeight={800}
          align="center"
          color="white"
          gutterBottom
        >
          {title}
        </Typography>
        <Typography paragraph align="center" color="white" variant="h6">
          {children}
        </Typography>
      </Container>
    </Box>
  );
};

const ApplyProcess = () => {
  return (
    <>
      <Head>
        <title>PCSHS Admissions</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box display="flex" flexDirection="column" height="100%">
        <Container>
          <ApplyInformation
            backgroundImage="url(/pcshsPictures/PSATest.jpg)"
            title="PSAT Online"
          >
            Pasig Science Admission Test (PSAT) Online is a web-based assessment
            that aims to measure the aptitude of students in various areas such
            as verbal, mathematical, analytical, and scientific thinking. This
            test was also designed to measure their ability to perform well in
            the future under a science-oriented curriculum.
          </ApplyInformation>
          <Table>
            <TableHead>
              <TableRow>
                <StyledTableCell>Subject</StyledTableCell>
                <StyledTableCell align="right">
                  Time Allotment&nbsp;(m)
                </StyledTableCell>
                <StyledTableCell align="right">No. of Items</StyledTableCell>
              </TableRow>
            </TableHead>
            <TableBody>
              {PSATRows.map((row) => (
                <StyledTableRow key={row.subject}>
                  <StyledTableCell component="th" scope="row">
                    {row.subject}
                  </StyledTableCell>
                  <StyledTableCell align="right">{row.time}</StyledTableCell>
                  <StyledTableCell align="right">{row.items}</StyledTableCell>
                </StyledTableRow>
              ))}
            </TableBody>
          </Table>
        </Container>

        <Box sx={{ backgroundColor: "#03045e" }} pt={8} pb={8} mt={8} mb={4}>
          <Container
            sx={{
              display: "flex",
              justifyContent: "center",
              alignItems: "center",
              flexDirection: "column",
              color: "white",
            }}
          >
            <Typography variant="h4" align="center" fontWeight={800}>
              GETTING READY FOR PSAT ONLINE
            </Typography>
            <Typography variant="h6" align="center" mt={4}>
              All students and parents are required to attend the general
              orientation to be conducted virtually. In this orientation, you
              will be provided with access to the examination platform and a
              step-by-step guide on how to take the admission test online. Make
              sure to follow our{" "}
              <a
                href="https://www.facebook.com/pcshs.edu"
                rel="noopener noreferrer"
                target="_blank"
                style={{ color: "gold" }}
              >
                official Facebook page
              </a>{" "}
              for schedules and other updates.
            </Typography>
          </Container>
        </Box>

        <Container>
          <ApplyInformation
            backgroundImage="url(/pcshsPictures/study.jpg)"
            title="Before the Test"
          >
            Prepare for the test by ensuring that you have proper internet
            connection, being in a clean and peaceful environment, and making
            sure that the equipments needed to take the exam are ready to go.
            When you are ready, go to an online video conferencing platform,
            then stream and record your screen while taking the test.
          </ApplyInformation>

          <ApplyInformation
            backgroundImage="url(/pcshsPictures/review.jpg)"
            title="During the Test"
          >
            The 70-question multiple-choice exam must be completed in under 110
            minutes. Make sure to observe honesty in taking the exam, as
            cheating will lead to an automatic disqualification. The exam is
            confidential and it cannot be reproduced in any manner at any time.
          </ApplyInformation>

          <ApplyInformation
            backgroundImage="url(/pcshsPictures/submit.png)"
            title="Submit the Test"
          >
            Save the recording and submit through{" "}
            <a
              href="https://bit.ly/psat2021"
              rel="noopener noreferrer"
              target="_blank"
              style={{ color: "gold", textDecoration: "none" }}
            >
              this link
            </a>
            . <br />
            Your filename should follow this format: Last Name_First Name_Grade
            Level (e.g. Gomez_Richard_G7).
          </ApplyInformation>
        </Container>

        <Box sx={{ backgroundColor: "#03045e" }} pt={8} pb={8}>
          <Container
            sx={{
              display: "flex",
              justifyContent: "center",
              alignItems: "center",
              flexDirection: "column",
              color: "white",
            }}
          >
            <Typography variant="h4" align="center" fontWeight={800} mt={4}>
              Support
            </Typography>
            <Typography variant="h5" align="center" mt={4}>
              If you have any questions, please contact us at 628-2226 or
              728-7041 or send us an email at admission.pcshs@gmail.com.
            </Typography>
          </Container>
        </Box>
      </Box>
    </>
  );
};

export default ApplyProcess;
