import { Typography, Container, Box, Link, IconButton } from "@mui/material";
import {
  Timeline,
  TimelineItem,
  TimelineOppositeContent,
  TimelineSeparator,
  TimelineConnector,
  TimelineDot,
  TimelineContent,
} from "@mui/lab";
import Head from "next/head";
import styles from "../styles/About.module.css";
import VisibilityIcon from "@mui/icons-material/Visibility";
import FlagIcon from "@mui/icons-material/Flag";
import DomainIcon from "@mui/icons-material/Domain";
import PeopleIcon from "@mui/icons-material/People";
import FmdGoodIcon from "@mui/icons-material/FmdGood";
import { Contacts, Objectives } from "../utils/staticResource";

const About = () => {
  return (
    <>
      <Head>
        <title>About PCSHS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <video autoPlay muted loop id="myVideo" className={styles.pcshsVideo}>
        <source
          src="https://video.wixstatic.com/video/99a79f_546d779f086f41469f6612347b2c6581/1080p/mp4/file.mp4"
          type="video/mp4"
        />
        Your browser does not support HTML5 video.
      </video>

      <Container>
        <Box mb={16}>
          <Box display="flex" alignItems="center" justifyContent="center">
            <VisibilityIcon fontSize="large" />
          </Box>
          <Typography variant="h3" fontWeight={800} align="center" mb={2}>
            Our Vision
          </Typography>
          <Typography paragraph align="justify" variant={"h5"}>
            PASIG CITY SCIENCE HIGH SCHOOL (PCSHS) is envisioned to be a world
            class institution that is globally and locally competitive and
            responsive to the ever-changing needs of the times, especially in
            the fields of Science and Technology.
          </Typography>
        </Box>

        <Box display="flex" alignItems="center" justifyContent="center">
          <FlagIcon fontSize="large" />
        </Box>
        <Typography
          variant={"h3"}
          fontWeight={800}
          align="center"
          sx={{ marginBottom: "16px" }}
        >
          Our Mission
        </Typography>
        <Typography paragraph align="justify" variant={"h5"}>
          PCSHS&apos; mission is to fully develop well-rounded, science and
          technology-oriented students, nurturing and gender-sensitive persons,
          and future leaders with a vision for excellence.
        </Typography>
      </Container>

      <Container>
        <Box id="objectives">
          <Typography
            variant="h3"
            fontWeight={800}
            align="center"
            mt={16}
            mb={2}
            sx={{ color: "black" }}
          >
            Our Objectives
          </Typography>

          {Objectives.map(({ icon, description }) => (
            <Box display="flex" alignItems="center" mb={4} key={description}>
              {icon}
              <Typography
                paragraph
                textAlign="justify"
                variant={"body1"}
                sx={{ m: 0 }}
              >
                {description}
              </Typography>
            </Box>
          ))}
        </Box>
      </Container>

      <Container>
        <Typography align="center" variant="h3" fontWeight={800} pt={16} mb={8}>
          Our History
        </Typography>

        <Typography variant="h4" align="center" gutterBottom>
          Year 2004
        </Typography>
        <Timeline position="alternate" sx={{ paddingBottom: "64px" }}>
          <TimelineItem>
            <TimelineOppositeContent
              sx={{ m: "auto 0" }}
              variant="body2"
              fontWeight={600}
            >
              October 7, 2004
            </TimelineOppositeContent>
            <TimelineSeparator>
              <TimelineConnector />
              <TimelineDot color="success">
                <FmdGoodIcon />
              </TimelineDot>
              <TimelineConnector />
            </TimelineSeparator>
            <TimelineContent sx={{ py: "12px", px: 2 }}>
              <Typography variant="h6" paragraph>
                Pasig City Science Highschool was founded with the support and
                determination of former Mayor Soledad C. Eusebio, Hon. Mayor
                Vicente P. Eusebio, and the members of the City Council.
              </Typography>
            </TimelineContent>
          </TimelineItem>
          <TimelineItem>
            <TimelineOppositeContent
              sx={{ m: "auto 0" }}
              fontWeight={600}
              variant="body2"
            >
              Year 2005
            </TimelineOppositeContent>
            <TimelineSeparator>
              <TimelineConnector />
              <TimelineDot color="primary">
                <PeopleIcon />
              </TimelineDot>
              <TimelineConnector />
            </TimelineSeparator>
            <TimelineContent sx={{ py: "12px", px: 2 }}>
              <Typography variant="h6" paragraph>
                Faculties enrolled, entrance exams administered, grading
                standards set, and scholarship programs.
              </Typography>
            </TimelineContent>
          </TimelineItem>
          <TimelineItem>
            <TimelineOppositeContent
              sx={{ m: "auto 0" }}
              fontWeight={600}
              variant="body2"
            >
              Summer of 2006
            </TimelineOppositeContent>
            <TimelineSeparator>
              <TimelineConnector />
              <TimelineDot color="secondary">
                <DomainIcon />
              </TimelineDot>
              <TimelineConnector />
            </TimelineSeparator>
            <TimelineContent sx={{ py: "12px", px: 2 }}>
              <Typography variant="h6" paragraph>
                Upgraded facilities, establishing the dream school, and the
                creation of the PCSHS Logo and Hymn.
              </Typography>
            </TimelineContent>
          </TimelineItem>
        </Timeline>
      </Container>

      <Box className={styles.contactUs} id="contacts">
        <Typography
          variant="h3"
          fontWeight={800}
          align="center"
          mt={4}
          mb={2}
          color="#e9c46a"
        >
          Contact Us
        </Typography>

        <Box display="flex" justifyContent="space-evenly">
          {Contacts.map(({ icon, link }) => (
            <Box mr={2} key={link}>
              <Link href={link} target="_blank">
                <IconButton size="large">{icon}</IconButton>
              </Link>
            </Box>
          ))}
        </Box>
      </Box>
    </>
  );
};

export default About;
