import { Typography, Fade, Container, Grid, Slide } from "@mui/material";
import Head from "next/head";
import Image from "next/image";
import { Box } from "@mui/system";
import History from "../Components/About/Parts/History";
import VisibilitySensor from "react-visibility-sensor";
import Vision from "../public/pcshsPictures/vision.jpeg";
import Mission from "../public/pcshsPictures/mission.jpg";
import { ReactNode } from "react";
import ContactUs from "../Components/About/Parts/Contact";
import Objectives from "../Components/About/Parts/Objective";

const Main = ({
  image,
  children,
  reverse = false,
}: {
  image: string | StaticImageData;
  children: ReactNode;
  reverse?: boolean;
}) => {
  return (
    <VisibilitySensor partialVisibility>
      {({ isVisible }) => (
        <Grid
          container
          spacing={1}
          sx={{ paddingTop: "120px", paddingBottom: "120px" }}
          direction={reverse ? "row-reverse" : "row"}
        >
          <Slide direction="right" in={isVisible} mountOnEnter unmountOnExit>
            <Grid
              item
              xs={12}
              md={6}
              sx={{
                display: "flex",
                justifyContent: "center",
                alignItems: "center",
              }}
            >
              <Image
                src={image}
                placeholder="blur"
                alt="PCSHS School Image"
                width="600"
                height="420"
              />
            </Grid>
          </Slide>

          <Fade timeout={1000} in={isVisible}>
            <Grid
              item
              xs={12}
              md={6}
              sx={{
                display: "flex",
                flexDirection: "column",
                alignItems: "center",
                justifyContent: "center",
              }}
            >
              {children}
            </Grid>
          </Fade>
        </Grid>
      )}
    </VisibilitySensor>
  );
};

const About = () => {
  return (
    <>
      <Head>
        <title>About PCSHS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <video
        autoPlay
        muted
        loop
        id="myVideo"
        style={{
          width: "100%",
          height: "100vh",
          objectFit: "cover",
          filter: "brightness(50%)",
        }}
      >
        <source
          src="https://video.wixstatic.com/video/99a79f_546d779f086f41469f6612347b2c6581/1080p/mp4/file.mp4"
          type="video/mp4"
        />
        Your browser does not support HTML5 video.
      </video>

      <Box
        sx={{
          backgroundImage: "url(/pcshslogo.png)",
          backgroundSize: "cover",
          backgroundAttachment: "fixed",
        }}
      >
        <Box sx={{ backdropFilter: "brightness(25%)" }}>
          <Container>
            <Main image={Vision}>
              <Typography
                variant="h3"
                align="center"
                sx={{ marginBottom: "16px" }}
              >
                Our Vision
              </Typography>
              <Typography paragraph align="center" variant="h5">
                PASIG CITY SCIENCE HIGH SCHOOL (PCSHS) is envisioned to be a
                world class institution that is globally and locally competitive
                and responsive to the ever-changing needs of the times,
                especially in the fields of Science and Technology.
              </Typography>
            </Main>

            <Main image={Mission} reverse={true}>
              <Typography
                variant="h3"
                align="center"
                sx={{ marginBottom: "16px" }}
              >
                Our Mission
              </Typography>
              <Typography paragraph align="center" variant="h5">
                PCSHS&apos; mission is to fully develop well-rounded, science
                and technology-oriented students, nurturing and gender-sensitive
                persons, and future leaders with a vision for excellence.
              </Typography>
            </Main>
          </Container>
        </Box>
      </Box>

      <Box>
        <Container>
          <Typography
            align="center"
            variant="h3"
            pt={24}
            mb={16}
            sx={{ color: "black" }}
          >
            Our Objectives
          </Typography>

          <Objectives />
        </Container>
      </Box>

      <Box
        sx={{
          backgroundImage: "url(/pcshsPictures/vision.jpeg)",
          backgroundSize: "cover",
          backgroundAttachment: "fixed",
        }}
      >
        <Box sx={{ backdropFilter: "brightness(25%)" }}>
          <Container>
            <Typography align="center" variant="h3" pt={24} mb={8}>
              Our History
            </Typography>

            <VisibilitySensor partialVisibility>
              {({ isVisible }) => (
                <Fade in={isVisible} timeout={1000}>
                  <Box overflow="auto">
                    <History />
                  </Box>
                </Fade>
              )}
            </VisibilitySensor>
          </Container>
        </Box>
      </Box>

      <ContactUs />
    </>
  );
};

export default About;
